import { createContext, useContext, useEffect, useState } from 'react';

import { getItem, setItem } from '@/utils/secureStorage';

export type AppLanguage = 'en' | 'hi';

type TranslationKey = keyof typeof english;
type TranslationParams = Record<string, string | number>;
type LanguageContextValue = {
  language: AppLanguage;
  setLanguage: (language: AppLanguage) => void;
  t: (key: TranslationKey, params?: TranslationParams) => string;
  tripStatus: (status: string) => string;
};

const LANGUAGE_STORAGE_KEY = 'transitops_language';

const english = {
  home: 'Home',
  trips: 'Trips',
  profile: 'Profile',
  openTab: 'Open {{tab}}',
  language: 'Language',
  english: 'English',
  hindi: 'हिन्दी',
  back: 'Back',
  retry: 'Retry',
  signOut: 'Sign out',
  loading: 'Loading...',
  saving: 'Saving...',
  hide: 'Hide',
  show: 'Show',
  cancel: 'Cancel',
  okay: 'OK',
  driverAccess: 'DRIVER ACCESS',
  welcomeBack: 'Welcome back',
  loginSubtitle: 'Sign in to keep your fleet moving with confidence.',
  phoneNumber: 'Phone number',
  password: 'Password',
  enterPassword: 'Enter your password',
  forgotPassword: 'Forgot password?',
  signIn: 'Sign in',
  signingIn: 'Signing in...',
  needFleetAccess: 'Need access to your fleet?',
  contactAdministrator: 'Contact your administrator',
  enterCredentials: 'Enter your phone number and password to continue.',
  validPhone: 'Enter a valid phone number.',
  unableSignIn: 'Unable to sign in. Check your connection and try again.',
  securityCheck: 'SECURITY CHECK',
  createPassword: 'Create your password',
  temporaryPasswordNotice: 'Your temporary password must be replaced before you continue.',
  currentPassword: 'Current password',
  enterTemporaryPassword: 'Enter your temporary password',
  newPassword: 'New password',
  enterNewPassword: 'Enter a new password',
  setPassword: 'Set password',
  passwordMinLength: 'Your new password must be at least 8 characters.',
  unableChangePassword: 'Unable to change password.',
  driverDashboard: 'DRIVER DASHBOARD',
  greeting: 'Good morning, {{name}}',
  readyForWork: "You're ready for today's work",
  todaysAssignment: "TODAY'S ASSIGNMENT",
  openTrip: 'Open Trip →',
  noTripAssigned: 'No trip assigned yet',
  routeFromTo: '{{origin}} to {{destination}}',
  noSchedule: 'Your dispatcher will add an assignment here when your schedule is ready.',
  status: 'Status',
  statusDraft: 'Draft',
  statusPlanned: 'Planned',
  statusAssigned: 'Assigned',
  statusDispatched: 'In transit',
  statusCompleted: 'Completed',
  statusCancelled: 'Cancelled',
  quickAccess: 'Quick access',
  upcomingTrips: 'UPCOMING TRIPS',
  currentVehicle: 'CURRENT VEHICLE',
  driverOperations: 'DRIVER OPERATIONS',
  yourTrips: 'Your trips',
  assignmentsAppear: 'Assignments from your dispatcher will appear here.',
  noTrips: 'No trips yet',
  noTripsDescription: 'Once a trip is assigned to you, you will see its route, schedule, and status here.',
  vehicleNotAssigned: 'Vehicle not assigned',
  vehicleFallback: 'Vehicle',
  startsAt: 'Starts {{date}}',
  tripTitle: 'Trip #{{id}}',
  loadingTrip: 'Loading trip details...',
  errorLoadingTrip: 'Error Loading Trip',
  plannedRoute: 'Planned Route',
  distance: 'DISTANCE',
  assignedVehicle: 'ASSIGNED VEHICLE',
  operationsTelemetry: 'OPERATIONAL TELEMETRY',
  gpsAccuracyPoor: 'GPS accuracy is poor',
  offlineRetry: 'Offline - retrying GPS sync',
  staleGps: 'GPS update is stale',
  liveGps: 'Live GPS Sharing Active',
  gpsPermissionRequired: 'GPS Permission Required',
  connectingGps: 'Connecting GPS...',
  enableLocation: 'Enable Location',
  telemetrySyncs: 'TELEMETRY SYNCS',
  lastUpdate: 'LAST UPDATE',
  waiting: 'Waiting...',
  latitude: 'LATITUDE',
  longitude: 'LONGITUDE',
  loadingStatus: 'Loading',
  unloadingStatus: 'Unloading',
  loaded: 'Loaded',
  waitingToLoad: 'Waiting to load',
  unloaded: 'Unloaded',
  waitingToUnload: 'Waiting to unload',
  deliveryCheckpoints: 'DELIVERY CHECKPOINTS',
  tripPaused: 'Trip actions are paused until the issue is marked fixed.',
  markLoaded: 'Mark Loaded',
  markUnloaded: 'Mark Unloaded',
  checkpointsComplete: 'Loaded and unloaded. Ready to end trip.',
  issueFixed: 'Issue fixed',
  repairCost: 'Repair cost',
  receiptPending: 'Receipt pending',
  uploadBill: 'Upload Bill',
  uploading: 'Uploading...',
  billUploaded: 'Bill uploaded: {{name}}',
  billLabel: 'Bill',
  repairReceiptPending: 'Repair receipt pending',
  vehicleIssue: 'VEHICLE ISSUE · {{priority}}',
  fixing: 'Fixing',
  markFixed: 'Mark Fixed',
  updating: 'Updating...',
  reportVehicleIssue: 'Report vehicle issue',
  cancelReport: 'Cancel maintenance report',
  issueDetails: 'ISSUE DETAILS',
  describeVehicleIssue: 'Describe the vehicle issue',
  priority: 'PRIORITY',
  routine: 'Routine',
  urgent: 'Urgent',
  critical: 'Critical',
  repairCostLabel: 'REPAIR COST (₹)',
  receiptUpload: 'Upload repair bill',
  receiptUnavailable: 'Receipt not available yet',
  sendToMaintenance: 'Send to Maintenance',
  sending: 'Sending...',
  receiptAttached: 'The receipt is attached to maintenance history.',
  continueTrip: 'The report is closed. You can continue the trip.',
  tripCompleted: 'Trip Completed',
  tripCompletedMessage: 'Great job! Live GPS sharing has ended and fleet assets have been updated.',
  unableCompleteTrip: 'Unable to Complete Trip',
  tryAgain: 'Please try again.',
  loadConfirmed: 'Load Confirmed',
  unloadConfirmed: 'Unload Confirmed',
  loadConfirmedMessage: 'The truck is marked as loaded.',
  unloadConfirmedMessage: 'The delivery is marked as unloaded. You can now end the trip.',
  unableUpdateLoad: 'Unable to Update Load Status',
  addIssueDetails: 'Add issue details',
  issueDetailsMin: 'Describe the vehicle issue in at least 5 characters.',
  reportSent: 'Report Sent',
  reportSentMessage: 'The fleet manager can now review this vehicle issue in Maintenance.',
  unableSendReport: 'Unable to Send Report',
  unableUpdateIssue: 'Unable to Update Issue',
  billTooLarge: 'Bill is too large',
  billSizeLimit: 'Choose a PDF or image no larger than 10 MB.',
  unableSelectBill: 'Unable to Select Bill',
  enterRepairCost: 'Enter repair cost',
  repairCostHint: 'Enter the amount paid, or 0 if the repair had no cost.',
  billRequired: 'Bill required',
  billRequiredHint: 'Upload the bill now or mark the receipt as pending.',
  unableCompleteRepair: 'Unable to Complete Repair',
  issueFixedTitle: 'Issue Fixed',
  issueFixedMessage: 'Repair cost recorded. You can continue the trip.',
  billUploadedTitle: 'Bill Uploaded',
  unableUploadBill: 'Unable to Upload Bill',
  reportAsFixing: "Mark the report as 'Fixing' before completing the repair.",
  unableStartTrip: 'Unable to Start Trip',
  checkConnection: 'Please check your connection.',
  startTrip: 'Start Trip',
  startTripTitle: 'Start Trip',
  readyToDepart: 'Are you ready to depart? Live GPS location sharing will begin automatically.',
  batteryHint: 'For reliable background tracking, set TransitOps battery usage to Unrestricted in Android Settings. You can do this now or change it later.',
  locationShareActive: 'Live location sharing will continue during this trip.',
  batterySettings: 'Battery Settings',
  locationPermissionRequired: 'Location permission required',
  locationPermissionExplanation: 'Allow location access all the time so TransitOps can keep sharing the trip when the screen is locked.',
  openSettings: 'Open Settings',
  locationSetupFailed: 'Location setup failed',
  checkLocationSettings: 'Please check location settings.',
  tripStatus: 'Trip status: {{status}}. Live tracking inactive.',
  tripDraftMessage: 'This trip is {{status}}. Your dispatcher must assign it to you before you can start.',
  assignedGpsMessage: 'GPS location streaming will start automatically once you tap "Start Trip".',
  tripCompletedStatus: '✓ Trip completed. Location tracking deactivated.',
  gpsPermissionExplanation: 'TransitOps needs device location permission to stream real-time trip progress to dispatchers.',
  completeTrip: 'End Trip & Complete',
  plannedDistance: '{{distance}} km',
  cargoWeight: '{{weight}} kg',
  email: 'EMAIL',
  accountId: 'ACCOUNT ID',
  account: 'ACCOUNT',
  yourProfile: 'Your profile',
} as const;

const hindi: Record<TranslationKey, string> = {
  home: 'होम',
  trips: 'यात्राएँ',
  profile: 'प्रोफ़ाइल',
  openTab: '{{tab}} खोलें',
  language: 'भाषा',
  english: 'English',
  hindi: 'हिन्दी',
  back: 'वापस',
  retry: 'फिर कोशिश करें',
  signOut: 'साइन आउट',
  loading: 'लोड हो रहा है...',
  saving: 'सेव हो रहा है...',
  hide: 'छिपाएँ',
  show: 'दिखाएँ',
  cancel: 'रद्द करें',
  okay: 'ठीक है',
  driverAccess: 'ड्राइवर लॉगिन',
  welcomeBack: 'वापसी पर स्वागत है',
  loginSubtitle: 'अपने वाहन संचालन के लिए साइन इन करें।',
  phoneNumber: 'फ़ोन नंबर',
  password: 'पासवर्ड',
  enterPassword: 'अपना पासवर्ड दर्ज करें',
  forgotPassword: 'पासवर्ड भूल गए?',
  signIn: 'साइन इन',
  signingIn: 'साइन इन हो रहा है...',
  needFleetAccess: 'अपने बेड़े का एक्सेस चाहिए?',
  contactAdministrator: 'अपने व्यवस्थापक से संपर्क करें',
  enterCredentials: 'जारी रखने के लिए फ़ोन नंबर और पासवर्ड दर्ज करें।',
  validPhone: 'मान्य फ़ोन नंबर दर्ज करें।',
  unableSignIn: 'साइन इन नहीं हो सका। कनेक्शन जाँचकर फिर कोशिश करें।',
  securityCheck: 'सुरक्षा जाँच',
  createPassword: 'अपना पासवर्ड बनाएँ',
  temporaryPasswordNotice: 'जारी रखने से पहले अस्थायी पासवर्ड बदलें।',
  currentPassword: 'मौजूदा पासवर्ड',
  enterTemporaryPassword: 'अस्थायी पासवर्ड दर्ज करें',
  newPassword: 'नया पासवर्ड',
  enterNewPassword: 'नया पासवर्ड दर्ज करें',
  setPassword: 'पासवर्ड सेट करें',
  passwordMinLength: 'नया पासवर्ड कम से कम 8 अक्षरों का होना चाहिए।',
  unableChangePassword: 'पासवर्ड बदला नहीं जा सका।',
  driverDashboard: 'ड्राइवर डैशबोर्ड',
  greeting: 'सुप्रभात, {{name}}',
  readyForWork: 'आज के काम के लिए तैयार हैं',
  todaysAssignment: 'आज का काम',
  openTrip: 'यात्रा खोलें →',
  noTripAssigned: 'अभी कोई यात्रा नहीं दी गई',
  routeFromTo: '{{origin}} से {{destination}} तक',
  noSchedule: 'आपका शेड्यूल तैयार होने पर डिस्पैचर यात्रा जोड़ेगा।',
  status: 'स्थिति',
  statusDraft: 'ड्राफ्ट',
  statusPlanned: 'नियोजित',
  statusAssigned: 'सौंपी गई',
  statusDispatched: 'यात्रा जारी',
  statusCompleted: 'पूरी हुई',
  statusCancelled: 'रद्द',
  quickAccess: 'त्वरित पहुँच',
  upcomingTrips: 'आने वाली यात्राएँ',
  currentVehicle: 'मौजूदा वाहन',
  driverOperations: 'ड्राइवर संचालन',
  yourTrips: 'आपकी यात्राएँ',
  assignmentsAppear: 'डिस्पैचर द्वारा दी गई यात्राएँ यहाँ दिखेंगी।',
  noTrips: 'अभी कोई यात्रा नहीं',
  noTripsDescription: 'यात्रा मिलने पर उसका मार्ग, समय और स्थिति यहाँ दिखेगी।',
  vehicleNotAssigned: 'वाहन नहीं दिया गया',
  vehicleFallback: 'वाहन',
  startsAt: 'समय: {{date}}',
  tripTitle: 'यात्रा #{{id}}',
  loadingTrip: 'यात्रा की जानकारी लोड हो रही है...',
  errorLoadingTrip: 'यात्रा लोड नहीं हो सकी',
  plannedRoute: 'नियोजित मार्ग',
  distance: 'दूरी',
  assignedVehicle: 'दिया गया वाहन',
  operationsTelemetry: 'यात्रा जानकारी',
  gpsAccuracyPoor: 'GPS सटीकता कम है',
  offlineRetry: 'ऑफ़लाइन - GPS सिंक फिर से हो रहा है',
  staleGps: 'GPS अपडेट पुराना है',
  liveGps: 'लाइव GPS साझा हो रहा है',
  gpsPermissionRequired: 'GPS अनुमति आवश्यक है',
  connectingGps: 'GPS कनेक्ट हो रहा है...',
  enableLocation: 'लोकेशन चालू करें',
  telemetrySyncs: 'GPS सिंक',
  lastUpdate: 'अंतिम अपडेट',
  waiting: 'प्रतीक्षा में...',
  latitude: 'अक्षांश',
  longitude: 'देशांतर',
  loadingStatus: 'लोडिंग',
  unloadingStatus: 'अनलोडिंग',
  loaded: 'लोड हो गया',
  waitingToLoad: 'लोड होने की प्रतीक्षा',
  unloaded: 'अनलोड हो गया',
  waitingToUnload: 'अनलोड होने की प्रतीक्षा',
  deliveryCheckpoints: 'डिलीवरी चरण',
  tripPaused: 'समस्या ठीक होने तक यात्रा के काम रुके हैं।',
  markLoaded: 'लोड हो गया दर्ज करें',
  markUnloaded: 'अनलोड हो गया दर्ज करें',
  checkpointsComplete: 'लोड और अनलोड पूरा। अब यात्रा समाप्त कर सकते हैं।',
  issueFixed: 'समस्या ठीक हो गई',
  repairCost: 'मरम्मत लागत',
  receiptPending: 'रसीद बाकी है',
  uploadBill: 'बिल अपलोड करें',
  uploading: 'अपलोड हो रहा है...',
  billUploaded: 'बिल अपलोड हुआ: {{name}}',
  billLabel: 'बिल',
  repairReceiptPending: 'मरम्मत की रसीद बाकी है',
  vehicleIssue: 'वाहन की समस्या · {{priority}}',
  fixing: 'ठीक कर रहे हैं',
  markFixed: 'ठीक हो गया दर्ज करें',
  updating: 'अपडेट हो रहा है...',
  reportVehicleIssue: 'वाहन की समस्या बताएँ',
  cancelReport: 'रिपोर्ट रद्द करें',
  issueDetails: 'समस्या का विवरण',
  describeVehicleIssue: 'वाहन की समस्या लिखें',
  priority: 'प्राथमिकता',
  routine: 'सामान्य',
  urgent: 'तत्काल',
  critical: 'अति आवश्यक',
  repairCostLabel: 'मरम्मत लागत (₹)',
  receiptUpload: 'मरम्मत का बिल अपलोड करें',
  receiptUnavailable: 'रसीद अभी उपलब्ध नहीं है',
  sendToMaintenance: 'मेंटेनेंस को भेजें',
  sending: 'भेजा जा रहा है...',
  receiptAttached: 'रसीद मेंटेनेंस इतिहास में जोड़ दी गई है।',
  continueTrip: 'रिपोर्ट बंद है। आप यात्रा जारी रख सकते हैं।',
  tripCompleted: 'यात्रा पूरी हुई',
  tripCompletedMessage: 'शाबाश! लाइव GPS साझाकरण बंद हो गया है और वाहन उपलब्ध करा दिए गए हैं।',
  unableCompleteTrip: 'यात्रा पूरी नहीं हो सकी',
  tryAgain: 'फिर कोशिश करें।',
  loadConfirmed: 'लोड की पुष्टि हुई',
  unloadConfirmed: 'अनलोड की पुष्टि हुई',
  loadConfirmedMessage: 'ट्रक को लोड दर्ज कर दिया गया है।',
  unloadConfirmedMessage: 'डिलीवरी अनलोड दर्ज हुई। अब यात्रा समाप्त कर सकते हैं।',
  unableUpdateLoad: 'लोड स्थिति अपडेट नहीं हुई',
  addIssueDetails: 'समस्या का विवरण दें',
  issueDetailsMin: 'कम से कम 5 अक्षरों में समस्या लिखें।',
  reportSent: 'रिपोर्ट भेजी गई',
  reportSentMessage: 'फ्लीट मैनेजर अब मेंटेनेंस में समस्या देख सकता है।',
  unableSendReport: 'रिपोर्ट नहीं भेजी जा सकी',
  unableUpdateIssue: 'समस्या अपडेट नहीं हो सकी',
  billTooLarge: 'बिल बहुत बड़ा है',
  billSizeLimit: '10 MB तक की PDF या इमेज चुनें।',
  unableSelectBill: 'बिल नहीं चुना जा सका',
  enterRepairCost: 'मरम्मत लागत दर्ज करें',
  repairCostHint: 'भरी गई राशि दर्ज करें, या बिना लागत की मरम्मत के लिए 0 दर्ज करें।',
  billRequired: 'बिल आवश्यक है',
  billRequiredHint: 'अभी बिल अपलोड करें या रसीद बाकी होने का विकल्प चुनें।',
  unableCompleteRepair: 'मरम्मत पूरी नहीं हो सकी',
  issueFixedTitle: 'समस्या ठीक हुई',
  issueFixedMessage: 'मरम्मत लागत दर्ज है। आप यात्रा जारी रख सकते हैं।',
  billUploadedTitle: 'बिल अपलोड हुआ',
  unableUploadBill: 'बिल अपलोड नहीं हो सका',
  reportAsFixing: 'समस्या ठीक करने से पहले रिपोर्ट को ठीक कर रहे हैं चुनें।',
  unableStartTrip: 'यात्रा शुरू नहीं हो सकी',
  checkConnection: 'कनेक्शन जाँचकर फिर कोशिश करें।',
  startTrip: 'यात्रा शुरू करें',
  startTripTitle: 'यात्रा शुरू करें',
  readyToDepart: 'क्या आप रवाना होने के लिए तैयार हैं? लाइव GPS साझा करना अपने आप शुरू होगा।',
  batteryHint: 'भरोसेमंद बैकग्राउंड ट्रैकिंग के लिए Android Settings में TransitOps की बैटरी को Unrestricted करें। अभी करें या बाद में।',
  locationShareActive: 'इस यात्रा के दौरान लाइव लोकेशन साझा होगी।',
  batterySettings: 'बैटरी सेटिंग्स',
  locationPermissionRequired: 'लोकेशन अनुमति आवश्यक है',
  locationPermissionExplanation: 'स्क्रीन लॉक होने पर भी यात्रा की लोकेशन साझा करने के लिए TransitOps को हमेशा लोकेशन की अनुमति दें।',
  openSettings: 'सेटिंग खोलें',
  locationSetupFailed: 'लोकेशन सेटअप नहीं हुआ',
  checkLocationSettings: 'लोकेशन सेटिंग्स जाँचें।',
  tripStatus: 'यात्रा की स्थिति: {{status}}। लाइव ट्रैकिंग बंद है।',
  tripDraftMessage: 'यह यात्रा {{status}} है। शुरू करने से पहले डिस्पैचर को आपको इसे देना होगा।',
  assignedGpsMessage: 'यात्रा शुरू करें दबाते ही GPS साझा होना शुरू होगा।',
  tripCompletedStatus: '✓ यात्रा पूरी हुई। लोकेशन ट्रैकिंग बंद है।',
  gpsPermissionExplanation: 'डिस्पैचर को यात्रा की प्रगति दिखाने के लिए TransitOps को फोन की लोकेशन चाहिए।',
  completeTrip: 'यात्रा समाप्त करें',
  plannedDistance: '{{distance}} km',
  cargoWeight: '{{weight}} kg',
  email: 'ईमेल',
  accountId: 'अकाउंट आईडी',
  account: 'अकाउंट',
  yourProfile: 'आपकी प्रोफ़ाइल',
};

const LanguageContext = createContext<LanguageContextValue | null>(null);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<AppLanguage>('en');

  useEffect(() => {
    let isMounted = true;
    getItem(LANGUAGE_STORAGE_KEY)
      .then((stored) => {
        if (isMounted && (stored === 'en' || stored === 'hi')) setLanguageState(stored);
      })
      .catch(() => undefined);
    return () => { isMounted = false; };
  }, []);

  const setLanguage = (next: AppLanguage) => {
    setLanguageState(next);
    void setItem(LANGUAGE_STORAGE_KEY, next).catch(() => undefined);
  };

  const t = (key: TranslationKey, params: TranslationParams = {}) => {
    const template = (language === 'hi' ? hindi[key] : english[key]) as string;
    return template.replace(/\{\{(\w+)\}\}/g, (match, name: string) => String(params[name] ?? match));
  };

  const tripStatus = (status: string) => {
    const statusKey: Partial<Record<string, TranslationKey>> = {
      Draft: 'statusDraft',
      Planned: 'statusPlanned',
      Assigned: 'statusAssigned',
      Dispatched: 'statusDispatched',
      Completed: 'statusCompleted',
      Cancelled: 'statusCancelled',
    };
    const key = statusKey[status];
    return key ? t(key) : status;
  };

  return <LanguageContext.Provider value={{ language, setLanguage, t, tripStatus }}>{children}</LanguageContext.Provider>;
}

export function useLanguage() {
  const value = useContext(LanguageContext);
  if (!value) throw new Error('useLanguage must be used inside LanguageProvider.');
  return value;
}
